### ISSUE TITLE
imagic notebook RuntimeError: One of the differentiated Tensors does not require grad

### ISSUE THREAD

**Issue by TalTaiber** [justinpinkney/stable-diffusion#39]
Thank you for your great work, it is highly appreciated.

I am trying to run the imagic code from the notebook (`./notebooks/imagic.ipynb`). When running the first training loop for the text embedding, I get the following error:
`
Traceback (most recent call last):
  File "/snap/pycharm-community/302/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/302/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/wonder/PycharmProjects/Dreambooth-Stable-Diffusion/train_imagic.py", line 134, in <module>
    loss.backward()
  File "/home/wonder/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/wonder/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/wonder/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/home/wonder/PycharmProjects/Dreambooth-Stable-Diffusion/ldm/modules/diffusionmodules/util.py", line 139, in backward
    input_grads = torch.autograd.grad(
  File "/home/wonder/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/autograd/__init__.py", line 276, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: One of the differentiated Tensors does not require grad
`

I have tried changing the optimizer, and ensured that `pred_noise.requires_grad = True`.
Does anyone know how to solve this?

**Comment by TalTaiber** [comment]
I re-downloaded `[sd-v1-4-full-ema.ckpt](https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/blob/main/sd-v1-4-full-ema.ckpt)` and built a new virtual env. Now it works

**Comment by zhangvia** [comment]
did you run the code successfully?where is the definition of the quicksampler function and display?
